#ifndef RECOMENDATION_PARAMETER_VALUES_H
#define RECOMENDATION_PARAMETER_VALUES_H

#define ALPHA 15
#define EUCLIDEAN 1
#define COSINE 2
#define UNKNOWN_METRIC 0

#define K_VALUE 50
#endif //RECOMENDATION_PARAMETER_VALUES_H
